export const FETCH_CARD = 'FETCH_CARD';
export const FETCH_CARD_PENDING = 'FETCH_CARD_PENDING';
export const FETCH_CARD_FULFILLED = 'FETCH_CARD_FULFILLED';
export const FETCH_CARD_REJECTED = 'FETCH_CARD_REJECTED';
export const ITEM_DEL = 'ITEM_DEL';
export const ITEM_INC = 'ITEM_INC';
export const ITEM_DEC = 'ITEM_DEC';
